# The name of the input VCF file. 
input: test/test.vcf.gz

analysis_name: test

n_loci: 10

model:
    name: 2Pop
    tree: ""
    populations:
        Yoruba:
            - S_Yoruba-1
            - S_Yoruba-2
        French:
            - S_French-1
            - S_French-2

stat_regions_to_sample: 100

inference_parameters:
    # Maximum population size parameter
    q: 30000
    m: 2   
    t: 300000
    # Generation time in years
    u: 29
    L: 2.0
    b: 1.0
    -ima-path: /well/gerton/ccole/repos/IMa3/IMa3
