# The name of the input VCF file. 
input: "run/testing/subset.vcf.gz"

analysis_name: "pipe"

model:
    name: "2Pop"
    tree: ""
    populations:
        Yoruba:
            - S_Yoruba-1
            - S_Yoruba-2
        French:
            - S_French-1
            - S_French-2

